# Generated by Django 5.2.4 on 2025-07-30 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
    ]
