# Generated by Django 5.2.4 on 2025-07-31 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("WebDatabase", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Backbonetable",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_column="Name", max_length=20)),
                (
                    "length",
                    models.IntegerField(blank=True, db_column="Length", null=True),
                ),
                ("sequence", models.TextField(db_column="Sequence")),
                ("ori", models.CharField(db_column="Ori", max_length=20)),
                ("marker", models.CharField(db_column="Marker", max_length=20)),
                (
                    "species",
                    models.CharField(
                        blank=True, db_column="Species", max_length=50, null=True
                    ),
                ),
                (
                    "copynumber",
                    models.CharField(
                        blank=True, db_column="CopyNumber", max_length=20, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, db_column="Notes", null=True)),
                (
                    "scar",
                    models.CharField(
                        blank=True, db_column="Scar", max_length=500, null=True
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True, db_column="Alias", max_length=30, null=True
                    ),
                ),
                ("user", models.CharField(db_column="User", max_length=50)),
            ],
            options={
                "db_table": "backbonetable",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Parttable",
            fields=[
                (
                    "partid",
                    models.AutoField(
                        db_column="PartID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="Name", max_length=100, null=True
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True, db_column="Alias", max_length=100, null=True
                    ),
                ),
                ("lengthinlevel0", models.IntegerField(db_column="LengthInLevel0")),
                (
                    "level0sequence",
                    models.TextField(blank=True, db_column="Level0Sequence", null=True),
                ),
                (
                    "confirmedsequence",
                    models.TextField(
                        blank=True, db_column="ConfirmedSequence", null=True
                    ),
                ),
                (
                    "insertsequence",
                    models.TextField(blank=True, db_column="InsertSequence", null=True),
                ),
                (
                    "sourceorganism",
                    models.TextField(blank=True, db_column="SourceOrganism", null=True),
                ),
                (
                    "reference",
                    models.TextField(blank=True, db_column="Reference", null=True),
                ),
                ("note", models.TextField(blank=True, db_column="Note", null=True)),
                ("type", models.IntegerField(db_column="Type")),
                (
                    "user",
                    models.CharField(
                        blank=True, db_column="User", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "db_table": "parttable",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Plasmidneed",
            fields=[
                (
                    "plasmidid",
                    models.AutoField(
                        db_column="PlasmidID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, db_column="Name", max_length=20, null=True
                    ),
                ),
                ("oricloning", models.CharField(db_column="OriCloning", max_length=20)),
                ("orihost", models.CharField(db_column="OriHost", max_length=20)),
                (
                    "markercloning",
                    models.CharField(db_column="MarkerCloning", max_length=20),
                ),
                ("markerhost", models.CharField(db_column="MarkerHost", max_length=20)),
                ("level", models.CharField(db_column="Level", max_length=10)),
                ("length", models.IntegerField(db_column="Length")),
                ("sequenceconfirm", models.TextField(db_column="SequenceConfirm")),
                (
                    "plate",
                    models.CharField(
                        blank=True, db_column="Plate", max_length=100, null=True
                    ),
                ),
                ("state", models.IntegerField(db_column="State")),
                ("user", models.CharField(db_column="User", max_length=20)),
                (
                    "note",
                    models.CharField(
                        blank=True, db_column="Note", max_length=500, null=True
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True, db_column="Alias", max_length=30, null=True
                    ),
                ),
            ],
            options={
                "db_table": "plasmidneed",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Straintable",
            fields=[
                (
                    "strainid",
                    models.AutoField(
                        db_column="StrainID", primary_key=True, serialize=False
                    ),
                ),
                ("strainname", models.CharField(db_column="StrainName", max_length=20)),
                ("background", models.CharField(db_column="Background", max_length=20)),
                ("marker", models.CharField(db_column="Marker", max_length=30)),
                ("store", models.CharField(db_column="Store", max_length=100)),
                ("genotype", models.CharField(max_length=100)),
                ("type", models.IntegerField()),
            ],
            options={
                "db_table": "straintable",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Testdatatable",
            fields=[
                (
                    "testdataid",
                    models.AutoField(
                        db_column="TestDataID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "testdataname",
                    models.CharField(db_column="TestDataName", max_length=20),
                ),
                (
                    "purpose",
                    models.TextField(blank=True, db_column="Purpose", null=True),
                ),
                (
                    "standardstrain",
                    models.CharField(
                        blank=True, db_column="StandardStrain", max_length=30, null=True
                    ),
                ),
                (
                    "positivecontrol",
                    models.CharField(
                        blank=True,
                        db_column="PositiveControl",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "dataaddress",
                    models.TextField(blank=True, db_column="DataAddress", null=True),
                ),
                ("date", models.TextField(blank=True, db_column="Date", null=True)),
                ("strain", models.CharField(db_column="Strain", max_length=100)),
            ],
            options={
                "db_table": "testdatatable",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("uid", models.AutoField(primary_key=True, serialize=False)),
                ("uname", models.CharField(max_length=50)),
                ("email", models.CharField(blank=True, max_length=50, null=True)),
                ("create_time", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "user",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Partrputable",
            fields=[
                (
                    "prid",
                    models.AutoField(
                        db_column="PRID", primary_key=True, serialize=False
                    ),
                ),
                ("rpu", models.FloatField(db_column="RPU")),
                (
                    "teststrain",
                    models.CharField(
                        blank=True, db_column="TestStrain", max_length=50, null=True
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, db_column="Note", max_length=100, null=True
                    ),
                ),
                (
                    "partid",
                    models.ForeignKey(
                        db_column="PartID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="WebDatabase.parttable",
                    ),
                ),
            ],
            options={
                "db_table": "partrputable",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Parentplasmidtable",
            fields=[
                (
                    "ppid",
                    models.AutoField(
                        db_column="PPID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "parentplasmidid",
                    models.ForeignKey(
                        db_column="ParentPlasmidID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="parentplasmidtable_parentplasmidid_set",
                        to="WebDatabase.plasmidneed",
                    ),
                ),
                (
                    "sonplasmidid",
                    models.ForeignKey(
                        db_column="SonPlasmidID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="WebDatabase.plasmidneed",
                    ),
                ),
            ],
            options={
                "db_table": "parentplasmidtable",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TbPlasmidUserfileaddress",
            fields=[
                ("ufid", models.AutoField(primary_key=True, serialize=False)),
                ("fileaddress", models.TextField(blank=True, null=True)),
                (
                    "plasmidid",
                    models.ForeignKey(
                        blank=True,
                        db_column="plasmidid",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="WebDatabase.plasmidneed",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        blank=True,
                        db_column="userid",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="WebDatabase.user",
                    ),
                ),
            ],
            options={
                "db_table": "tb_plasmid_userfileaddress",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TbPartUserfileaddress",
            fields=[
                ("ufid", models.AutoField(primary_key=True, serialize=False)),
                ("fileaddress", models.TextField(blank=True, null=True)),
                (
                    "partid",
                    models.ForeignKey(
                        blank=True,
                        db_column="partid",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="WebDatabase.parttable",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        blank=True,
                        db_column="userid",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="WebDatabase.user",
                    ),
                ),
            ],
            options={
                "db_table": "tb_part_userfileaddress",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TbBackboneUserfileaddress",
            fields=[
                ("ufid", models.AutoField(primary_key=True, serialize=False)),
                ("fileaddress", models.TextField(blank=True, null=True)),
                (
                    "backboneid",
                    models.ForeignKey(
                        blank=True,
                        db_column="backboneid",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="WebDatabase.backbonetable",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        blank=True,
                        db_column="userid",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="WebDatabase.user",
                    ),
                ),
            ],
            options={
                "db_table": "tb_backbone_userfileaddress",
                "managed": True,
            },
        ),
    ]
