# Generated by Django 5.2.4 on 2025-11-18 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WebDatabase", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plasmidneed",
            name="customparentinformation",
        ),
        migrations.AddField(
            model_name="plasmidneed",
            name="CustomParentInfo",
            field=models.TextField(
                blank=True, db_column="CustomParentInformation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="plasmidneed",
            name="state",
            field=models.IntegerField(blank=True, db_column="State", null=True),
        ),
    ]
